# Generated by Django 5.2 on 2025-05-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('savings', 'Savings')], default='expense', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('savings', 'Savings')], default='expense', max_length=10),
        ),
    ]
